import fitz
import os
import pytesseract
from PIL import Image


def extract_pdf_ocr(path):
    """
    Extract all text from a PDF and return as a list of strings
    for each page. Uses OCR to extract txt from PDFs where 
    the text is contained in images.
    Generated by Copilot
    """
    doc = fitz.open(path)
    all_text = []

    for page in doc:
        # Render page to an image (300 DPI recommended for OCR)
        pix = page.get_pixmap(dpi=300)
        img = Image.frombytes("RGB", [pix.width, pix.height], pix.samples)

        # OCR the image
        text = pytesseract.image_to_string(img)
        all_text.append(text)

    return all_text


def extract_pdf_text_images(path):
    """
    Extract all text and images from a PDF and return.
    Generated with Copilot, modified to return instead of write to file
    """
    doc = fitz.open(path)
    pages_text = []
    images = []

    for page_index, page in enumerate(doc):
        # -----------------------------
        # 1. Extract TEXT
        # -----------------------------
        text_blocks = page.get_text("blocks")

        blocks = []
        for b in text_blocks:
            x0, y0, x1, y1, text, *_ = b
            # TODO - Duplicated code - rethink this eventually
            pages_text.append({
                "bbox": fitz.Rect(x0, y0, x1, y1),
                "text": text.strip(),
            })
            blocks.append({
                "bbox": fitz.Rect(x0, y0, x1, y1),
                "text": text.strip(),
            })

        # -----------------------------
        # 2. Extract IMAGES
        # -----------------------------
        for img_index, img in enumerate(page.get_image_info(xrefs=True)):
            xref = img["xref"]
            bbox = img["bbox"]

            # -----------------------------
            # 3. Find Nearest Text Block
            # -----------------------------
            def vertical_distance(block):
                return abs(block["bbox"].y1 - bbox.yo)

            # Choose block directly above the image
            above_blocks = [b for b in blocks if b["bbox"].y1 <= bbox.y0]

            if above_blocks:
                closest = min(above_blocks, key=vertical_distance)
                images.append({
                    # TODO - This is not very efficient. I should have a shared key 
                    # between text and images
                    "closest_text": closest["text"],
                    "image": img,
                })
            else:
                # TODO - kinda duplicated code. I can make this more efficient later
                images.append({
                    "closest_text": "",
                    "image": img,
                })

    doc.close()

    return pages_text, images

